name: Branch modification

on:
  push:
    branches:
      - modification
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Extract git-rev
        run: |
          $commitCount = git rev-list --count HEAD
          $shortHash = git rev-parse --short HEAD
          "GIT_REV=r$commitCount.$shortHash" | Out-File -FilePath $env:GITHUB_ENV -Append
          $env:GIT_REV

      - name: Setup Toolchain
        run: rustup default nightly-msvc

      - uses: Swatinem/rust-cache@v2

      - name: Set version in Cargo.toml
        run: |
          $files = @(
              './Cargo.toml'
              './yas/Cargo.toml'
              './yas-genshin/Cargo.toml'
              './yas-starrail/Cargo.toml'
          )
          [regex]$pattern = '(?<=version = ").*(?=")'
          foreach ($file in $files) {
              $pattern.Replace((Get-Content -Raw $file), "0.0.0-r$env:GIT_REV", 1) | Out-File -FilePath $file
          }

      - name: Build (Release)
        run: cargo build --release

      - name: Rename Outputs
        run: |
          Rename-Item target/release/yas_scanner_genshin.exe "yas_scanner_genshin_$env:GIT_REV.exe"
          Rename-Item target/release/yas_scanner_starrail.exe "yas_scanner_starrail_$env:GIT_REV.exe"

      - uses: actions/upload-artifact@v4
        with:
          name: yas_scanner_genshin_${{ env.GIT_REV }}
          path: target/release/yas_scanner_genshin_${{ env.GIT_REV }}.exe

      - uses: actions/upload-artifact@v4
        with:
          name: yas_scanner_starrail_${{ env.GIT_REV }}
          path: target/release/yas_scanner_starrail_${{ env.GIT_REV }}.exe
