name: Rust

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true

      - uses: Swatinem/rust-cache@v2

      - name: Build (Debug)
        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        run: cargo build

      - name: Build (Release)
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: cargo build --release

      - name: Upload artifact
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        uses: actions/upload-artifact@v3
        with:
          name: yas_scanner
          path: target/release/yas_scanner.exe
